# Generated by Django 5.2.6 on 2025-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="listings_bo_booking_e25590_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="listings_bo_listing_7352a3_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_li_listing_d29eec_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_li_locatio_4bc07d_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_li_host_id_add4f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="listings_re_review__8a3385_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="listings_re_listing_a2005b_idx",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="end_date",
            new_name="check_in",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="start_date",
            new_name="check_out",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="booking_id",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="host",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="listing_id",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="location",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="price_per_night",
        ),
        migrations.RemoveField(
            model_name="review",
            name="review_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
